import random

class GuessingGame:
    """
    I chose to include a class to organize my code and to keep everthing
    centrailized.
    """

    # Generate a random number between 1-10 and store it in a variable
    number = random.randint(1, 10)
    print(number)

    """
    Generate a message to the user asking their name. For better improvement 
    on the project I implemented simple error handling to control if the  
    input is not a string. The program will quit if the user does not provide the
    proper input.
    """
    user = input("Enter your name: ")

    if type(user) == str:
        print(f"Okay {user} I will guess a number between 1 and 10. You will "
              f"have 5 chances to guess the number: ")

        guesses = 0

        if type(guesses) is int:
            while guesses < 5:
                # Gather the number that the user guessed
                user_guess = int(input())

                # Once input is gathered increment the guess counter by 1
                guesses += 1

                """
                Implement a check to see if the if number the user provided is 
                greater or less than the random number generated by the 
                computer.
                """
                if user_guess < number:
                    print(f"Your guess is a little too low. Try again!")
                elif user_guess > number:
                    print(f"Your guess is a little too high. Try again!")
                else:
                    print(f"You guessed correct with {guesses} number of "
                          f"tries!")
                    break
        else:
            print("Your guess must be an integer.")
            quit()

    else:
        print("Please enter a valid name (it must be of type string).")
        quit()